"""new fields in user mode

Revision ID: 190f3ccbdba8
Revises: 1645cd7d6f50
Create Date: 2024-03-30 13:24:41.039402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '190f3ccbdba8'
down_revision = '1645cd7d6f50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_me', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_seen')
        batch_op.drop_column('about_me')

    # ### end Alembic commands ###
